export type Bank = {
    code: string;
    name: string
}

export const banks = [
    {code: "422589", name: "Ngân hàng TNHH MTV CIMB Việt Nam (CIMB)"},
    {code: "458761", name: "Ngân hàng TNHH MTV HSBC (Việt Nam) (HSBC)"},
    {code: "546034", name: "Ngân hàng số CAKE by VPBank (CAKE)"},
    {code: "546035", name: "Ngân hàng số Ubank by VPBank (Ubank)"},
    {code: "668888", name: "Ngân hàng Đại chúng TNHH Kasikornbank (KBank)"},
    {code: "796500", name: "DBS Bank Ltd - Chi nhánh TP. Hồ Chí Minh (DBSBank)"},
    {code: "801011", name: "Ngân hàng Nonghyup - Chi nhánh Hà Nội (Nonghyup)"},
    {code: "970400", name: "Ngân hàng TMCP Sài Gòn Công Thương (SaigonBank)"},
    {code: "970403", name: "Ngân hàng TMCP Sài Gòn Thương Tín (Sacombank)"},
    {code: "970405", name: "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam (Agribank)"},
    {code: "970406", name: "Ngân hàng TMCP Đông Á (DongABank)"},
    {code: "970407", name: "Ngân hàng TMCP Kỹ thương Việt Nam (Techcombank)"},
    {code: "970408", name: "Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu (GPBank)"},
    {code: "970409", name: "Ngân hàng TMCP Bắc Á (BacABank)"},
    {code: "970410", name: "Ngân hàng Standard Chartered Việt Nam (Standard Chartered)"},
    {code: "970412", name: "Ngân hàng TMCP Đại Chúng Việt Nam (PVcomBank)"},
    {code: "970414", name: "Ngân hàng Thương mại TNHH MTV Đại Dương (Oceanbank)"},
    {code: "970415", name: "Ngân hàng TMCP Công thương Việt Nam (VietinBank)"},
    {code: "970416", name: "Ngân hàng TMCP Á Châu (ACB)"},
    {code: "970418", name: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)"},
    {code: "970419", name: "Ngân hàng TMCP Quốc Dân (NCB)"},
    {code: "970421", name: "Ngân hàng Liên doanh Việt - Nga (VRB)"},
    {code: "970422", name: "Ngân hàng TMCP Quân đội (MBBank)"},
    {code: "970423", name: "Ngân hàng TMCP Tiên Phong (TPBank)"},
    {code: "970424", name: "Ngân hàng TNHH MTV Shinhan Việt Nam (ShinhanBank)"},
    {code: "970425", name: "Ngân hàng TMCP An Bình (ABBANK)"},
    {code: "970426", name: "Ngân hàng TMCP Hàng Hải (MSB)"},
    {code: "970427", name: "Ngân hàng TMCP Việt Á (VietABank)"},
    {code: "970428", name: "Ngân hàng TMCP Nam Á (NamABank)"},
    {code: "970429", name: "Ngân hàng TMCP Sài Gòn (SCB)"},
    {code: "970430", name: "Ngân hàng TMCP Xăng dầu Petrolimex (PGBank)"},
    {code: "970431", name: "Ngân hàng TMCP Xuất Nhập khẩu Việt Nam (Eximbank)"},
    {code: "970432", name: "Ngân hàng TMCP Việt Nam Thịnh Vượng (VPBank)"},
    {code: "970433", name: "Ngân hàng TMCP Việt Nam Thương Tín (VietBank)"},
    {code: "970434", name: "Ngân hàng TNHH Indovina (IndovinaBank)"},
    {code: "970436", name: "Ngân hàng TMCP Ngoại Thương Việt Nam (Vietcombank)"},
    {code: "970437", name: "Ngân hàng TMCP PT Thành phố Hồ Chí Minh (HDBank)"},
    {code: "970438", name: "Ngân hàng TMCP Bảo Việt (BaoVietBank)"},
    {code: "970439", name: "Ngân hàng TNHH MTV Public Việt Nam (PublicBank)"},
    {code: "970440", name: "Ngân hàng TMCP Đông Nam Á (SeABank)"},
    {code: "970441", name: "Ngân hàng TMCP Quốc tế Việt Nam (VIB)"},
    {code: "970442", name: "Ngân hàng TNHH MTV Hong Leong Việt Nam (HongLeong)"},
    {code: "970443", name: "Ngân hàng TMCP Sài Gòn - Hà Nội (SHB)"},
    {code: "970444", name: "Ngân hàng TM TNHH MTV Xây dựng Việt Nam (CBBank)"},
    {code: "970446", name: "Ngân hàng Hợp tác xã Việt Nam (COOPBANK)"},
    {code: "970448", name: "Ngân hàng TMCP Phương Đông (OCB)"},
    {code: "970449", name: "Ngân hàng TMCP Bưu Điện Liên Việt (LienVietPostBank)"},
    {code: "970452", name: "Ngân hàng TMCP Kiên Long (KienLongBank)"},
    {code: "970454", name: "Ngân hàng TMCP Bản Việt (VietCapitalBank)"},
    {code: "970455", name: "Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội (IBKHN)"},
    {code: "970456", name: "Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh TP. Hồ Chí Minh (IBKHCM)"},
    {code: "970457", name: "Ngân hàng TNHH MTV Woori Việt Nam (Woori)"},
    {code: "970458", name: "Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh (United Overseas)"},
    {code: "970462", name: "Ngân hàng Kookmin - Chi nhánh Hà Nội (KookminHN)"},
    {code: "970463", name: "Ngân hàng Kookmin - Chi nhánh TP. Hồ Chí Minh (KookminHCM)"},
];